-- Rekapitulasi jumlah rekening yang dimiliki setiap nasabah

-- Answer below

SELECT CUSTOMER.CUST_ID , CUSTOMER.CUST_FIRSTNAME , CUSTOMER.CUST_LASTNAME ,  CUSTOMER.CUST_GENDER , CUSTOMER.CUST_CITY , COUNT(ACCOUNT.ACC_NUMBER) as  account_owned
FROM CUSTOMER 
    LEFT JOIN ACCOUNT ACCOUNT ON CUSTOMER.CUST_ID = ACCOUNT.ACC_OWNER
GROUP BY CUSTOMER.CUST_ID, CUSTOMER.CUST_FIRSTNAME, CUSTOMER.CUST_LASTNAME , CUSTOMER.CUST_GENDER , CUSTOMER.CUST_CITY 
ORDER BY account_owned DESC;